const swaggerJsdoc = require('swagger-jsdoc');
const options = {
    swaggerDefinition: {
        // Like the one described here: https://swagger.io/specification/#infoObject
        info: {
            title: 'Feed',
            version: '1.0.0',
            description: 'Test Express API with autogenerated swagger doc'
        },
    },
    apis: ['./routers/*.js'],
};

module.exports = swaggerJsdoc(options);